# AI CLI Agent Configuration Example
# Copy this to ~/.config/ai-cli-agent/config.toml and modify as needed

# OpenRouter API Key (required)
# Get your API key from https://openrouter.ai
openrouter_api_key = "your_api_key_here"

# AI Model to use (default: "openai/gpt-4")
# Available models:
# - openai/gpt-4
# - openai/gpt-4-turbo
# - openai/gpt-3.5-turbo
# - anthropic/claude-2
# - anthropic/claude-instant-1
# - google/palm-2-chat-bison
# - google/palm-2-codechat-bison
# - meta-llama/llama-2-70b-chat
# - meta-llama/llama-2-13b-chat
# - mistralai/mistral-7b-instruct
# - mistralai/mixtral-8x7b-instruct
model = "openai/gpt-4"

# Working directory (default: current directory)
# Can be absolute or relative path
work_dir = "/path/to/your/project"

# Maximum tokens for AI responses (default: 4000)
max_tokens = 4000

# Temperature for AI responses (0.0 to 2.0, default: 0.7)
# Lower values = more focused, higher values = more creative
temperature = 0.7

# Request timeout in seconds (default: 120)
timeout_seconds = 120

# Auto-save configuration changes (default: true)
auto_save = true

# Enable file backups before editing (default: true)
backup_enabled = true

# Backup directory (default: ".ai_cli_backups")
backup_dir = ".ai_cli_backups"

# Additional settings (optional)
# These are not currently used but reserved for future features

# Logging level (optional)
# log_level = "info"

# Maximum file size to read in bytes (optional)
# max_file_size = 1048576  # 1MB

# Allowed file extensions for editing (optional)
# allowed_extensions = ["rs", "py", "js", "html", "css", "md", "txt"]

# Blocked file patterns (optional)
# blocked_patterns = ["*.exe", "*.dll", "*.so", "*.dylib"]

# Custom system prompt (optional)
# system_prompt = "You are an expert software developer assistant."